version : '3'

services:
  db:
    image: postgres
  
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data  

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  redis_data:
